### ISSUE TITLE
Empty Input on Redmine 3.4

### ISSUE THREAD

**Issue by virtualmarc** [martin-denizet/redmine_custom_js#1]
After upgrading from Redmine 3.3 to 3.4 the plugin still works but the input box is empty.

Same problem as in the redmine_custom_css plugin here:
https://github.com/martin-denizet/redmine_custom_css/issues/13

**Comment by virtualmarc** [comment]
I create a pull request to fix this

**Comment by martin-denizet** [comment]
Merged and published. Thank you! :)
